repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
  -   repo: git@github.com:Yelp/detect-secrets
      rev: v0.14.3
      hooks:
      -   id: detect-secrets
          args: ['--baseline', '.secrets.baseline']
          exclude: .*/tests/.*
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.720
      hooks:
      -   id: mypy
          exclude: .*/tests/.*
  -   repo: https://gitlab.com/pycqa/flake8
      rev: '3.8.4'
      hooks:
      -   id: flake8
          exclude: .*/tests/.*

